<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Description>An unstyled, accessible, headless UI component library built for Blazor (WebAssembly, Server) and .NET MAUI Blazor Hybrid applications.</Description>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BaseRz.JS\BaseRz.JS.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="BaseRz.Tests" />
  </ItemGroup>

</Project>
